version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitFeatureTestProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/GitFeatureTestProject
  gitUsername: PoojaAnandGit
  gitBranch: main
